### ISSUE TITLE
Unclear how to filter by element type

### ISSUE THREAD

**Issue by multimeric** [JuanCouste/overpass-ql-ts#18]
I can see methods for filtering by tag etc (https://github.com/JuanCouste/overpass-ql-ts/wiki/Tags), but I think the element type such as `way`, `node` etc isn't a tag? Would it be possible to update the wiki with an example of this?

**Comment by JuanCouste** [comment]
Hi, I see there is some confusion in how you are trying to use the package, I'll try to clarify some concepts.

Overpass queries are split-up into statements, these operate on sets that may contain node, ways, relations, etc.
They generally take some inputs and produce an output consisting of node, ways, relations, etc.

ie:  [Recurse down](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Recurse_down_(%3E)):  This statement outputs the "building blocks" of intputs, ie from a street it may output the houses, street lamps, crossings, that are included in it.

The most common statement you'll be using though, is the [query statement](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#The_Query_Statement).
It outputs elements that satisfy a set of [filters](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Filters), of which you've seen [byTags](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#By_tag_(has-kv)).
By tags checks an element tags for equality [name = "some name"], existance [!population] or similarity [name~".*city"].
There are many other filters though, you can filter by bounding box, by radius around something, by ids, etc.

The query statement operates on nodes, ways, relations, etc, you need to specify which one.
ie:
(imagine south, west, north and east are numbers)
```typescript
node.byTags({ name: /.*city/, capital: "yes" }).and(c =>c.bbox([south, west, north, east]))
```
Would yield:
```
node [name~".*city"] [capital="yes] (south, west, north, east)
```

I would recommend looking at [Statements](https://github.com/JuanCouste/overpass-ql-ts/wiki/Statements), though its outdated,
You can also use [Githubs' search feature](https://github.com/search?q=repo%3AJuanCouste%2Foverpass-ql-ts%20byTags&type=code) to look for examples of usage.
[Overpass wiki](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL) may help you get a better understanding of how everything works.

Cheers!

**Comment by multimeric** [comment]
Thanks. They key thing I missed is that you `s.<element type>.<query>`. I think it would help to throw in some `s.way` as well as `s.node` in the examples.
